@startuml
'https://plantuml.com/class-diagram
left to right direction
skinparam dpi 150
skinparam defaultTextAlignment center
skinparam wrapWidth 250
skinparam classAttributeIconSize 0

package edu.hitsz.basic {
    abstract class AbstractFlyingObject {
        # locationX, locationY
        # speedX, speedY
        # width, height
        
        + forward()
        + crash(flyingObject): boolean
        + getLocationX(), getLocationY()
        + getImage(), getWidth(), getHeight()
        + vanish()
    }
}

package edu.hitsz.aircraft {
    abstract class AbstractAircraft {
        # hp, maxHp
        # power, direction
        
        + decreaseHp()
        + getHp(), getPower()
        + {abstract} shoot(): List<BaseBullet>
    }

    abstract class AbstractEnemyAircraft extends AbstractAircraft {
        + forward()
    }

    class HeroAircraft {
        - MAX_HP, instance
        - shootStrategy
        
        + getInstance()
        + addHp()
        + setShootStrategy()
        + forward(), shoot()
    }

    class MobEnemy {
        + forward(), shoot()
    }

    class EliteEnemy {
        - PROP_DROP_RATE, PROP_SPEED_Y
        - shootStrategy
        
        + shoot(), createProp()
    }

    class ElitePlusEnemy {
        - moveSpeedX, MOVE_CYCLE
        - PROP_DROP_RATE, PROP_SPEED_Y
        - shootStrategy
        
        + forward(), shoot(), createProp()
    }

    class AceEnemy {
        - moveSpeedX, MOVE_CYCLE
        - PROP_DROP_RATE, PROP_SPEED_Y
        - shootStrategy
        
        + forward(), shoot(), createProp()
    }

    class BossEnemy {
        - moveSpeedX, MOVE_CYCLE
        - PROP_SPEED_Y
        - shootStrategy
        
        + forward(), shoot(), createProp()
    }

    AbstractAircraft <|-- AbstractEnemyAircraft
    AbstractEnemyAircraft <|-- MobEnemy
    AbstractEnemyAircraft <|-- EliteEnemy
    AbstractEnemyAircraft <|-- ElitePlusEnemy
    AbstractEnemyAircraft <|-- AceEnemy
    AbstractEnemyAircraft <|-- BossEnemy
    AbstractAircraft <|-- HeroAircraft
}

package edu.hitsz.bullet {
    abstract class BaseBullet {
        - power
        
        + forward()
        + getPower()
    }

    class HeroBullet
    class EnemyBullet

    BaseBullet <|-- HeroBullet
    BaseBullet <|-- EnemyBullet
}

package edu.hitsz.prop {
    abstract class AbstractProp extends AbstractFlyingObject {
        + {abstract} activate(hero): void
        + forward()
    }

    class BloodProp {
        + activate(hero): void
    }

    class FireProp {
        - powerUpStrategy
        + activate(hero): void
    }

    class SuperFireProp {
        - powerUpStrategy
        + activate(hero): void
    }

    class FreezeProp {
        + activate(hero): void
    }

    class BombProp {
        + activate(hero): void
    }

    AbstractProp <|-- BloodProp
    AbstractProp <|-- FireProp
    AbstractProp <|-- SuperFireProp
    AbstractProp <|-- FreezeProp
    AbstractProp <|-- BombProp
}

package edu.hitsz.strategy {
    interface ShootStrategy {
        + shoot(aircraft): List<BaseBullet>
    }

    class SingleShotStrategy implements ShootStrategy
    class TripleSpreadStrategy implements ShootStrategy
    class EnemySingleRowStrategy implements ShootStrategy
    class EnemyDoubleRowStrategy implements ShootStrategy
    class EnemyFanShotStrategy implements ShootStrategy

    interface FirePowerUpStrategy {
        + activate(hero): void
    }

    class FirePowerUpStrategy implements FirePowerUpStrategy
    class FirePlusPowerUpStrategy implements FirePowerUpStrategy

    ShootStrategy <|-- SingleShotStrategy
    ShootStrategy <|-- TripleSpreadStrategy
    ShootStrategy <|-- EnemySingleRowStrategy
    ShootStrategy <|-- EnemyDoubleRowStrategy
    ShootStrategy <|-- EnemyFanShotStrategy
    FirePowerUpStrategy <|-- FirePowerUpStrategy
    FirePowerUpStrategy <|-- FirePlusPowerUpStrategy
}

package edu.hitsz.factory {
    interface EnemyFactory
    class PropFactory
    class EnemyFactoryManager
    class MobEnemyFactory implements EnemyFactory
    class EliteEnemyFactory implements EnemyFactory
    class AceEnemyFactory implements EnemyFactory
    class BossEnemyFactory implements EnemyFactory

    EnemyFactory <|-- MobEnemyFactory
    EnemyFactory <|-- EliteEnemyFactory
    EnemyFactory <|-- AceEnemyFactory
    EnemyFactory <|-- BossEnemyFactory
}

package edu.hitsz.application {
    class ImageManager
    class HeroController
    class Game
    class Main
}

AbstractFlyingObject <|-- AbstractAircraft
AbstractFlyingObject <|-- BaseBullet
AbstractFlyingObject <|-- AbstractProp

@enduml
